### PR TITLE
fix: Call correct event so doors now can be toggled

### PR DESCRIPTION
**Pull request by rasm945i**
## Description

Currently an invalid event is called when toggling the doors. I call the correct event.

## Checklist

- [ X ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [ X ] My pull request fits the contribution guidelines & code conventions.

### CODE REVIEW

**Comment by solareon** [comment]
I see the fixes for the radial menu but what are all these additional changes with moving out the vehicle menu into a separate file?

**Comment by rasm945i** [comment]
This is very awkward. I think I accidentally pushed the wrong thing. I made personal changes (removed things and adjusted when menus are shown) which is what you mention.
It was only supposed to be changes to the config, I'm unsure how I messed up so bad, I apologize.

**Comment by rasm945i** [comment]
It's only the first commit, the one starting with "fix: " that's supposed to be pulled. I have no clue why the rest got smushed into this pullrequest

**Comment by BerkieBb** [comment]
Revert everything besides the changes in the config, they are not necessary. The cl_vehicle stuff should be in a separate PR

**Comment by rasm945i** [comment]
I hope I did it right.
TIL that the first thing I do after forking something, is to create a branch for my personal adjustments to avoid this kind of mess.

**Review by solareon — APPROVED** [review]

**Review by BerkieBb — APPROVED** [review]

**Pull request merged**
