### PR TITLE
Revert "Gang menu integration" because im banned

### PR DESCRIPTION
**Pull request by onscripts**
Reverts QBCore-Remastered/qb-radialmenu#1

### CODE REVIEW

**Comment by Manason** [comment]
Why are you wanting to revert this?

**Comment by D4isDAVID** [comment]
@Manason
The reason is clearly stated in the title

**Comment by Manason** [comment]
> The reason is clearly stated in the title

I might be missing the context or giving the author the benefit of the doubt. Am I correct in assuming that the author did not put up this PR to improve the code base, but instead to make it worse?

**Comment by D4isDAVID** [comment]
@Manason 
Indeed, because he was banned from the Discord server

**Comment by Manason** [comment]
Closing this and #5 out then. PRs which make the code base worse are not accepted.

**Comment by ognscripts** [comment]
> > The reason is clearly stated in the title
> 
> 
> 
> I might be missing the context or giving the author the benefit of the doubt. Am I correct in assuming that the author did not put up this PR to improve the code base, but instead to make it worse?
> 
> 

I just want to revert the changes i did because i got banned from the discord server without a legit reason.

**Comment by Manason** [comment]
@zZOGZz That's irrelevant. See my post above about PRs being required to improve the code base.

**Comment by ognscripts** [comment]
> @zZOGZz That's irrelevant. See my post above about PRs being required to improve the code base.

Its irrelevant for you. Have some respect for the people. Nobody will make any effort to be paid with a ban. The code is not going to be worse, it will just be the same as before.

**Comment by D4isDAVID** [comment]
@zZOGZz 
You want to revert commits that improve the resource, which worsens it.

**Comment by Manason** [comment]
@zZOGZz By contributing to an open source project, you gave a gift to the "people" of the FiveM community. When you put up a PR you do that with the understanding that you can't undo that action. Wanting to hurt the community over your beef with some discord staff I find to be petty and inappropriate.

**Pull request closed without merging**
